# Inventaire généré automatiquement — ne pas éditer à la main
# Regénérer avec : make inventory

[bastion]
bastion ansible_host=35.181.173.29 ansible_user=ec2-user

[sonde]
sonde ansible_host=15.237.52.221 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ec2-user@35.181.173.29 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[all:vars]
ansible_ssh_private_key_file=c:/MASTER2/CLOUD/AWS/infra3/td2-99-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
